services:
    _defaults:
        autowire: true
        autoconfigure: true

    Becklyn\OrderedFormBundle\Form\Extension\FormPositionExtension:
        tags:
            -   name: form.type_extension
                extended_type: 'Symfony\Component\Form\Extension\Core\Type\FormType'


    Becklyn\OrderedFormBundle\Form\ResolvedType\OrderedResolvedFormTypeFactory: ~
