language: php

git:
    depth: 1

php:
    - 7.1
    - 7.4

before_install:
    - COMPOSER_MEMORY_LIMIT=-1 composer global require localheinz/composer-normalize bamarni/composer-bin-plugin --no-interaction --prefer-dist --no-progress --no-suggest
    - COMPOSER_MEMORY_LIMIT=-1 composer bin coveralls require php-coveralls/php-coveralls --no-interaction --prefer-dist --no-progress --no-suggest

install:
    - COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction --prefer-dist --no-progress --no-suggest
    - COMPOSER_MEMORY_LIMIT=-1 composer bin all install --no-interaction --prefer-dist --no-progress
    - mkdir -p build/logs

script:
    - composer normalize --indent-size 4 --indent-style space --dry-run
    - ./vendor/bin/php-cs-fixer fix --diff --config vendor-bin/test/vendor/becklyn/php-cs/.php_cs.dist --dry-run --no-interaction
    - ./vendor/bin/simple-phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml
    - ./vendor/bin/phpstan analyse --memory-limit 4G --ansi -c vendor-bin/test/vendor/becklyn/php-cs/phpstan/lib.neon src --no-interaction --no-progress

after_script:
    - travis_retry php vendor/bin/php-coveralls
